/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConstructButton: typeof import('@sa-net/components')['ConstructButton']
    ConstructInput: typeof import('@sa-net/components')['ConstructInput']
    ConstructLayout: typeof import('@sa-net/components')['ConstructLayout']
    ConstructLink: typeof import('@sa-net/components')['ConstructLink']
    ConstructPage: typeof import('@sa-net/components')['ConstructPage']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
